spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lmsacciodb?createTableIfNotExists=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: accio-library-management-system

server:
  port: 6060